title: Ella Wood | Glaciologist & PhD Researcher
author: Ella Wood
description: PhD Researcher in Remote Sensing and Glaciology at the University of St Andrews.
url: "https://himal-ella.github.io"
remote_theme: jekyll/minima

sitemap:
  exclude:
    - "/google*.html"

# This section prevents the "Subscribe" button from generating
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

minima:
  skin: dark

header_pages:
  - about.md
  - cv.md
  - contact.md
